// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Asset = { id: string, campaign_id: string, uploaded_by: string, filename: string, content_type: string, size_bytes: bigint, created_at: string, };
