// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request type for creating a new map
 */
export type CreateMapRequest = { name: string, grid_enabled: boolean, grid_size_px: number, grid_scale: number, width_squares: number, height_squares: number, };
