// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerType } from "./LayerType";

/**
 * Request for creating a layer
 */
export type CreateLayerRequest = { name: string, layer_type: LayerType, dm_only: boolean, };
