// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrawingType = "freehand" | "line" | "rectangle" | "circle" | "polygon" | "aoe_cone" | "aoe_cube" | "aoe_sphere" | "aoe_line";
