// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerType } from "./LayerType";

export type MapLayer = { id: string, map_id: string, name: string, layer_type: LayerType, sort_order: number, visible: boolean, locked: boolean, opacity: number, dm_only: boolean, created_at: string, };
