// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for placing an image on a layer
 */
export type PlaceMapImageRequest = { asset_id: string, x: number, y: number, width: number, height: number, rotation: number, opacity: number, };
