// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FogCell } from "./FogCell";

export type RevealFogRequest = { cells: Array<FogCell>, revealed: boolean, };
