// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageType } from "./ChatMessageType";

export type SendChatMessageRequest = { character_id: string | null, message_type: ChatMessageType, content: string, whisper_target_ids: Array<string>, };
