// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BonusTypeDef } from "./BonusTypeDef";
import type { SheetSection } from "./SheetSection";

export type SheetSchema = { sections: Array<SheetSection>, bonus_types: Array<BonusTypeDef>, };
