// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewCombatant } from "./NewCombatant";

export type StartEncounterRequest = { combatants: Array<NewCombatant>, };
