// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarVisibility } from "./BarVisibility";

export type TokenBar = { label: string, current: number, max: number, color: string, visibility: BarVisibility, };
