// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for updating a map image
 */
export type UpdateMapImageRequest = { x: number | null, y: number | null, width: number | null, height: number | null, rotation: number | null, opacity: number | null, };
