// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenBar } from "./TokenBar";

/**
 * Request type for updating a token (all fields optional for PATCH)
 */
export type UpdateTokenRequest = { name: string | null, asset_id: string | null | null, owner_id: string | null | null, x: number | null, y: number | null, size: number | null, rotation: number | null, bars: Array<TokenBar> | null, status_markers: Array<string> | null, };
