// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorState } from "./DoorState";
import type { WallType } from "./WallType";

export type UpdateWallRequest = { x1: number | null, y1: number | null, x2: number | null, y2: number | null, wall_type: WallType | null, door_state: DoorState | null, };
