// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddBonusRequest = { field_id: string, source: string, bonus_type: string, value: bigint, };
