// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CampaignRole } from "./CampaignRole";

export type CampaignMember = { campaign_id: string, user_id: string, role: CampaignRole, display_name: string, joined_at: string, };
