// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BonusEntry } from "./BonusEntry";
import type { JsonValue } from "./serde_json/JsonValue";

export type CharacterExport = { format: string, game_system_id: string, game_system_version: string, name: string, fields: { [key in string]: JsonValue }, bonuses: { [key in string]: Array<BonusEntry> }, exported_at: string, };
