// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateDrawingRequest } from "./CreateDrawingRequest";
import type { CreateTokenRequest } from "./CreateTokenRequest";
import type { PlaceMapImageRequest } from "./PlaceMapImageRequest";
import type { UpdateDrawingRequest } from "./UpdateDrawingRequest";
import type { UpdateMapImageRequest } from "./UpdateMapImageRequest";
import type { UpdateTokenRequest } from "./UpdateTokenRequest";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Messages sent from client to server
 */
export type ClientMessage = { "type": "Ping" } | { "type": "CreateToken", "payload": { layer_id: string, token: CreateTokenRequest, } } | { "type": "MoveToken", "payload": { token_id: string, x: number, y: number, } } | { "type": "UpdateToken", "payload": { token_id: string, patch: UpdateTokenRequest, } } | { "type": "DeleteToken", "payload": { token_id: string, } } | { "type": "CreateDrawing", "payload": { layer_id: string, drawing: CreateDrawingRequest, } } | { "type": "UpdateDrawing", "payload": { drawing_id: string, patch: UpdateDrawingRequest, } } | { "type": "DeleteDrawing", "payload": { drawing_id: string, } } | { "type": "ReorderLayers", "payload": { map_id: string, layer_ids: Array<string>, } } | { "type": "PlaceMapImage", "payload": { layer_id: string, image: PlaceMapImageRequest, } } | { "type": "UpdateMapImage", "payload": { image_id: string, patch: UpdateMapImageRequest, } } | { "type": "DeleteMapImage", "payload": { image_id: string, } } | { "type": "JoinSession", "payload": { campaign_id: string, } } | { "type": "LeaveSession", "payload": Record<symbol, never> } | { "type": "RequestFullState", "payload": { map_id: string, } } | { "type": "UpdateCharacterFields", "payload": { character_id: string, fields: { [key in string]: JsonValue }, } } | { "type": "AddCharacterBonus", "payload": { character_id: string, field_id: string, source: string, bonus_type: string, value: bigint, } } | { "type": "RemoveCharacterBonus", "payload": { character_id: string, bonus_id: string, } } | { "type": "UpdateCharacterBonus", "payload": { character_id: string, bonus_id: string, source: string | null, bonus_type: string | null, value: bigint | null, } } | { "type": "LinkTokenToCharacter", "payload": { token_id: string, character_id: string | null, } };
