// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Messages sent from client to server
 */
export type ClientMessage = { "type": "Ping" };
