// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Combatant = { id: string, encounter_id: string, character_id: string | null, name: string, initiative_value: number, sort_order: number, is_active: boolean, };
