// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A connected user in a session
 */
export type ConnectedUser = { user_id: string, display_name: string, role: string, };
