// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCharacterRequest = { game_system_id: string, name: string, portrait_asset_id: string | null, };
