// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoorState } from "./DoorState";
import type { WallType } from "./WallType";

export type CreateWallRequest = { x1: number, y1: number, x2: number, y2: number, wall_type: WallType, door_state: DoorState, };
