// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOption } from "./ChoiceOption";

export type FieldType = { "type": "Integer", "config": { min: bigint | null, max: bigint | null, } } | { "type": "Text", "config": { max_length: number | null, } } | { "type": "LongText" } | { "type": "Boolean" } | { "type": "Choice", "config": { options: Array<ChoiceOption>, } } | { "type": "AbilityScore" } | { "type": "StatBlock", "config": { label: string, } } | { "type": "ResourcePool", "config": { max_field: string | null, } } | { "type": "BonusStacked", "config": { base_expression: string | null, allowed_bonus_types: Array<string>, } };
