// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldType } from "./FieldType";
import type { WidthHint } from "./WidthHint";
import type { JsonValue } from "./serde_json/JsonValue";

export type FieldDef = { id: string, name: string, field_type: FieldType, default_value: JsonValue | null, derived: boolean, visible: boolean, group: string | null, width_hint: WidthHint, };
