// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandoutVisibility } from "./HandoutVisibility";

export type HandoutSummary = { id: string, title: string, visibility: HandoutVisibility, player_ids: Array<string>, updated_at: string, };
