// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Drawing } from "./Drawing";
import type { Map } from "./Map";
import type { MapLayer } from "./MapLayer";
import type { Token } from "./Token";

/**
 * Full map state including all entities on the map
 */
export type MapFullState = { map: Map, layers: Array<MapLayer>, tokens: Array<Token>, drawings: Array<Drawing>, };
