// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapImage = { id: string, layer_id: string, asset_id: string, x: number, y: number, width: number, height: number, rotation: number, opacity: number, };
