// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagonalMode } from "./DiagonalMode";
import type { MapLayer } from "./MapLayer";
import type { SnapMode } from "./SnapMode";

/**
 * Full map response with layers included
 */
export type MapWithLayers = { layers: Array<MapLayer>, id: string, campaign_id: string, name: string, grid_enabled: boolean, grid_size_px: number, grid_color: string, grid_opacity: number, grid_line_width: number, grid_scale: number, grid_scale_unit: string, snap_mode: SnapMode, diagonal_mode: DiagonalMode, width_squares: number, height_squares: number, created_at: string, updated_at: string, };
