// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewCombatant = { character_id: string | null, name: string, initiative_value: number, };
