// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectionLayout = { "type": "Grid", "config": { columns: number, } } | { "type": "List" } | { "type": "Table", "config": { columns: Array<string>, } } | { "type": "Tabs", "config": { tabs: Array<string>, } };
