// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectedUser } from "./ConnectedUser";
import type { Drawing } from "./Drawing";
import type { Map } from "./Map";
import type { MapImage } from "./MapImage";
import type { MapLayer } from "./MapLayer";
import type { Token } from "./Token";
import type { UpdateDrawingRequest } from "./UpdateDrawingRequest";
import type { UpdateMapImageRequest } from "./UpdateMapImageRequest";
import type { UpdateTokenRequest } from "./UpdateTokenRequest";

/**
 * Messages sent from server to client
 */
export type ServerMessage = { "type": "Pong" } | { "type": "Error", "payload": { code: string, message: string, } } | { "type": "TokenCreated", "payload": { layer_id: string, token: Token, created_by: string, } } | { "type": "TokenMoved", "payload": { token_id: string, x: number, y: number, moved_by: string, } } | { "type": "TokenUpdated", "payload": { token_id: string, patch: UpdateTokenRequest, updated_by: string, } } | { "type": "TokenDeleted", "payload": { token_id: string, deleted_by: string, } } | { "type": "DrawingCreated", "payload": { layer_id: string, drawing: Drawing, } } | { "type": "DrawingUpdated", "payload": { drawing_id: string, patch: UpdateDrawingRequest, } } | { "type": "DrawingDeleted", "payload": { drawing_id: string, } } | { "type": "LayerCreated", "payload": { layer: MapLayer, } } | { "type": "LayerUpdated", "payload": { layer: MapLayer, } } | { "type": "LayerDeleted", "payload": { layer_id: string, } } | { "type": "LayersReordered", "payload": { map_id: string, layer_ids: Array<string>, } } | { "type": "MapImagePlaced", "payload": { layer_id: string, image: MapImage, } } | { "type": "MapImageUpdated", "payload": { image_id: string, patch: UpdateMapImageRequest, } } | { "type": "MapImageDeleted", "payload": { image_id: string, } } | { "type": "SessionJoined", "payload": { user_id: string, campaign_id: string, connected_users: Array<ConnectedUser>, } } | { "type": "UserJoined", "payload": { user_id: string, display_name: string, } } | { "type": "UserLeft", "payload": { user_id: string, display_name: string, } } | { "type": "FullState", "payload": { map: Map, layers: Array<MapLayer>, tokens: Array<Token>, drawings: Array<Drawing>, } };
