// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldDef } from "./FieldDef";
import type { SectionLayout } from "./SectionLayout";

export type SheetSection = { id: string, name: string, layout: SectionLayout, fields: Array<FieldDef>, };
