// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for updating a layer
 */
export type UpdateLayerRequest = { name: string | null, visible: boolean | null, locked: boolean | null, opacity: number | null, dm_only: boolean | null, };
