// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Request type for updating a drawing
 */
export type UpdateDrawingRequest = { points: JsonValue | null, stroke_color: string | null, stroke_width: number | null, stroke_opacity: number | null, fill_color: string | null | null, fill_opacity: number | null, };
