// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCharacterRequest = { name: string | null, portrait_asset_id: string | null | null, visible_to_players: boolean | null, };
