// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagonalMode } from "./DiagonalMode";
import type { SnapMode } from "./SnapMode";

/**
 * Request type for updating map settings
 */
export type UpdateMapRequest = { name: string | null, grid_enabled: boolean | null, grid_size_px: number | null, grid_color: string | null, grid_opacity: number | null, grid_line_width: number | null, grid_scale: number | null, grid_scale_unit: string | null, snap_mode: SnapMode | null, diagonal_mode: DiagonalMode | null, width_squares: number | null, height_squares: number | null, };
