// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateBonusRequest = { source: string | null, bonus_type: string | null, value: bigint | null, };
